version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "daily"
    reviewers:
      - "janishorsts"
    commit-message:
      prefix: "chore(deps)"
    allow:
      - dependency-type: "all"
    groups:
      aws:
        patterns:
          - "github.com/aws/*"
      google:
        patterns:
          - "cloud.google.com/*"
      grpc:
        patterns:
          - "google.golang.org/*"
      otel:
        patterns:
          - "go.opentelemetry.io/*"
      x:
        patterns:
          - "golang.org/x/*"

