run:
  build-tags:
    - integration
  timeout: 2m
issues:
  exclude-dirs:
    - pkg/pb
linters:
  enable-all: true
  disable:
    - asasalint
    - depguard
    - dupl
    - err113
    - exhaustruct
    - forbidigo
    - funlen
    - gci
    - ginkgolinter
    - goconst
    - gochecknoglobals
    - gochecknoinits
    - gocyclo
    - godox
    - gofmt
    - goheader
    - goimports
    - gomodguard
    - gosmopolitan
    - grouper
    - inamedparam
    - loggercheck
    - maintidx
    - nlreturn
    - nonamedreturns
    - promlinter
    - tagliatelle
    - tenv # Duplicate feature in another linter. Replaced by usetesting.
    - testableexamples
    - testpackage
    - tparallel
    - varnamelen
    - wastedassign
    - whitespace
    - zerologlint
linters-settings:
  cyclop:
    max-complexity: 30
  govet:
    enable-all: true
  predeclared:
    ignore: ""
  wrapcheck:
    ignoreSigs:
      - .Errorf(
      - errors.New(
      - errors.Unwrap(
      - errors.Join(
      - status.Error(
      - .Wrap(
      - .Wrapf(
      - .WithMessage(
      - .WithMessagef(
      - .WithStack(

