run:
  build-tags:
    - integration
  timeout: 2m
issues:
  exclude-dirs:
    - pkg/pb
linters:
  enable-all: true
  disable:
    - asasalint
    - deadcode
    - depguard
    - dupl
    - exhaustivestruct
    - exhaustruct
    - forbidigo
    - funlen
    - gci
    - ginkgolinter
    - goconst
    - gochecknoglobals
    - gochecknoinits
    - gocyclo
    - godox
    - goerr113
    - gofmt
    - goheader
    - goimports
    - golint
    - gomodguard
    - gosmopolitan
    - grouper
    - ifshort
    - inamedparam
    - interfacer
    - loggercheck
    - maintidx
    - maligned
    - nlreturn
    - nonamedreturns
    - nosnakecase
    - promlinter
    - revive
    - scopelint
    - structcheck
    - tagliatelle
    - testableexamples
    - testpackage
    - thelper
    - tparallel
    - varcheck
    - varnamelen
    - wastedassign
    - whitespace
    - zerologlint
linters-settings:
  cyclop:
    max-complexity: 30
  gosec:
    excludes:
      - G601 # False positive in go 1.22+. Implicit memory aliasing of items from a range statement.
  govet:
    enable-all: true
  predeclared:
    ignore: ""
