version: "2"
run:
  build-tags:
    - integration
linters:
  default: all
  disable:
    - asasalint
    - depguard
    - dupl
    - err113
    - exhaustruct
    - forbidigo
    - funlen
    - ginkgolinter
    - gochecknoglobals
    - gochecknoinits
    - goconst
    - gocyclo
    - godox
    - goheader
    - gomodguard
    - gosmopolitan
    - grouper
    - inamedparam
    - loggercheck
    - maintidx
    - nlreturn
    - nonamedreturns
    - promlinter
    - tagliatelle
    - testableexamples
    - testpackage
    - tparallel
    - varnamelen
    - wastedassign
    - whitespace
    - zerologlint
  settings:
    cyclop:
      max-complexity: 30
    govet:
      enable-all: true
    wrapcheck:
      ignore-sigs:
        - .Errorf(
        - errors.New(
        - errors.Unwrap(
        - errors.Join(
        - status.Error(
        - .Wrap(
        - .Wrapf(
        - .WithMessage(
        - .WithMessagef(
        - .WithStack(
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - pkg/pb
formatters:
  enable:
    - gofumpt
  exclusions:
    generated: lax
    paths:
      - pkg/pb
