run:
  build-tags:
    - integration
  timeout: 2m
  skip-dirs:
    - pkg/pb
linters:
  enable-all: true
  disable:
   - asasalint
   - cyclop
   - deadcode
   - depguard
   - dogsled
   - dupl
   - dupword
   - exhaustivestruct
   - exhaustruct
   - forbidigo
   - forcetypeassert
   - funlen
   - gci
   - ginkgolinter
   - goconst
   - gocheckcompilerdirectives
   - gochecknoglobals
   - gochecknoinits
   - godox
   - goerr113
   - gofmt
   - goheader
   - goimports
   - golint
   - gomoddirectives
   - gomodguard
   - gosmopolitan
   - grouper
   - ifshort
   - inamedparam
   - interfacebloat
   - interfacer
   - ireturn
   - loggercheck
   - maintidx
   - maligned
   - mirror
   - musttag
   - nilnil
   - nlreturn
   - nonamedreturns
   - nosnakecase
   - nosprintfhostport
   - predeclared
   - promlinter
   - reassign
   - revive
   - rowserrcheck
   - scopelint
   - sqlclosecheck
   - structcheck
   - stylecheck
   - tagalign
   - tagliatelle
   - tenv
   - testableexamples
   - testpackage
   - thelper
   - tparallel
   - usestdlibvars
   - varcheck
   - varnamelen
   - wastedassign
   - whitespace
   - zerologlint
linters-settings:
  govet:
    enable-all: true
  importas:
    alias:
      - pkg: go.expect.digital/translate/pkg/pb/translate/v1
        alias: translatev1
