run:
  build-tags:
    - integration
  timeout: 2m
  skip-dirs:
    - pkg/pb
linters:
  enable:
   - forcetypeassert
   - mirror
   - musttag
  disable:
   - asasalint
   - gci
   - gochecknoglobals
   - gochecknoinits
   - goconst
   - godox
   - gofmt
   - deadcode
   - depguard
   - dupl
   - exhaustivestruct
   - exhaustruct
   - forbidigo
   - funlen
   - ginkgolinter
   - goimports
   - golint
   - gomodguard
   - grouper
   - ifshort
   - inamedparam
   - interfacer
   - loggercheck
   - maligned
   - nonamedreturns
   - nosnakecase
   - promlinter
   - revive
   - scopelint
   - structcheck
   - testpackage
   - varcheck
   - zerologlint
linters-settings:
  govet:
    enable-all: true
  importas:
    alias:
      - pkg: go.expect.digital/translate/pkg/pb/translate/v1
        alias: translatev1
