services:
  mysql:
    image: mysql:9.4.0@sha256:91447968e66961302339ec4dc4d385f5e1a957d98e63c7d52ecf8b1de0907346
    container_name: mysql
    hostname: mysql
    networks:
      - translate
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=translate
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    healthcheck:
      test: "mysqladmin status"
      interval: 1s
      timeout: 60s
      retries: 60
    restart: always

  jaeger:
    image: jaegertracing/all-in-one:1.60@sha256:4fd2d70fa347d6a47e79fcb06b1c177e6079f92cba88b083153d56263082135e
    container_name: jaeger
    hostname: jaeger
    networks:
      - translate
    ports:
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "4317:4317"
      - "4318:4318"
      - "14250:14250"
      - "14268:14268"
      - "14269:14269"
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    restart: always

  envoy:
    image: envoyproxy/envoy:v1.35-latest@sha256:4d496918618a7ebd6c71ae8285e31ebff092f3a0a5ad642d50decf4a54eb2456
    ports:
      - "8080:8080"
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml
    networks:
      - translate
    restart: always

networks:
  translate:
