version: "3"
name: "translate"

services:
  mysql:
    image: mysql:8.0.33
    container_name: mysql
    hostname: mysql
    networks:
      - translate
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=translate
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    healthcheck:
      test: "/etc/init.d/mysql status"
      interval: 1s
      timeout: 10s
      retries: 10
    restart: always

  jaeger:
    image: jaegertracing/all-in-one:1.47
    container_name: jaeger
    hostname: jaeger
    networks:
      - translate
    ports:
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "4317:4317"
      - "4318:4318"
      - "14250:14250"
      - "14268:14268"
      - "14269:14269"
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    restart: always

  envoy:
    image: envoyproxy/envoy:v1.26-latest
    ports:
      - "8080:8080"
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml
    networks:
      - translate
    restart: always

networks:
  translate:
