name: CI

on:
  push:

env:
  EARTHLY_VERSION: 0.7.9

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: earthly/actions-setup@v1
        with:
          version: ${{ env.EARTHLY_VERSION }}
          use-cache: true
      - uses: actions/checkout@v3
      - name: Proto
        run: earthly +lint-proto
      - name: Migrate
        run: earthly +lint-migrate
      - name: GO
        run: earthly +lint-go
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: earthly/actions-setup@v1
        with:
          version: ${{ env.EARTHLY_VERSION }}
          use-cache: true
      - uses: actions/checkout@v3
      - name: Unit
        run: earthly +test-unit
      - name: Integration
        run: earthly --allow-privileged +test-integration
