name: CI

on:
  push:

env:
  EARTHLY_VERSION: 0.7.15

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: earthly/actions-setup@v1
        with:
          version: ${{ env.EARTHLY_VERSION }}
          use-cache: true
      - uses: actions/checkout@v3
      # Check if Generated Go files are up to date
      - name: GO proto up-to-date
        run: |
          earthly +proto
          if ! git diff --quiet; then
            echo "Generated Go files are not up to date"
            git diff --stat
            exit 1
          fi
        # LINT
      - name: Lint Proto
        run: earthly --ci +lint-proto
      - name: Lint Migrate
        run: earthly --ci +lint-migrate
      - name: Lint GO
        run: earthly --ci +lint-go
        # TEST
      - name: Test Unit
        run: earthly --ci +test-unit
      - name: Test Integration
        env:
          EARTHLY_ACCOUNT_TOKEN: ${{ secrets.EARTHLY_ACCOUNT_TOKEN }}
        run: |
          earthly account login --token "$EARTHLY_ACCOUNT_TOKEN"
          earthly --ci --allow-privileged +test-integration
