name: CI

on:
  push:

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: earthly/actions-setup@v1
        with:
          version: 0.7.2
          use-cache: true
      - uses: actions/checkout@v3
      - name: Proto
        run: earthly +lint-proto
      - name: Migrate
        run: earthly +lint-migrate
      - name: GO
        run: earthly +lint-go
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: earthly/actions-setup@v1
        with:
          version: 0.7.2
          use-cache: true
      - uses: actions/checkout@v3
      - name: Unit
        run: earthly +test-unit
      - name: Integration
        run: earthly --allow-privileged +test-integration
