name: CI

on:
  pull_request:

permissions:
  contents: write
  packages: write

jobs:
  check:
    runs-on: ubuntu-latest
    env:
      EARTHLY_REMOTE_CACHE: ghcr.io/translate-agent/ci-translate:cache
      FORCE_COLOR: 1
    steps:
      - uses: earthly/actions-setup@v1
        with:
          version: 0.8.15
          github-token: ${{ secrets.GITHUB_TOKEN }}
          use-cache: false
      - uses: actions/checkout@v4
      - name: Log in to the GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          # Use the new PAT secret instead of GITHUB_TOKEN
          password: ${{ secrets.GITHUB_TOKEN }}

      # Check if Generated Go files are up to date
      - name: GO proto up-to-date
        run: |
          earthly --ci +proto
          if ! git diff --quiet; then
            echo "Generated Go files are not up to date"
            git diff --stat
            exit 1
          fi
        # LINT
      - name: Lint Proto
        run: earthly --ci +lint-proto
      - name: Lint Migrate
        run: earthly --ci +lint-migrate
      - name: Lint GO
        run: earthly --ci +lint-go
        # TEST
      - name: Test Unit
        run: earthly --ci +test-unit
      - name: Test Integration
        if: ${{ github.actor != 'dependabot[bot]' }}
        env:
          EARTHLY_TOKEN: ${{ secrets.EARTHLY_TOKEN }}
        run: earthly --ci --allow-privileged +test-integration
  automerge:
    runs-on: ubuntu-latest
    needs: check
    permissions:
      contents: write
      pull-requests: write
    if: |
      github.ref_type == 'branch' &&
      startsWith(github.head_ref, 'dependabot/') &&
      github.actor == 'dependabot[bot]' &&
      github.repository == 'translate-agent/translate'
    steps:
      - name: Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@v2.4.0
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
      - name: Merge a PR
        if: |
          steps.metadata.outputs.update-type == 'version-update:semver-minor' &&
          (
            contains(steps.metadata.outputs.dependency-group, 'aws') ||
            contains(steps.metadata.outputs.dependency-group, 'google') ||
            contains(steps.metadata.outputs.dependency-group, 'otel') ||
            contains(steps.metadata.outputs.dependency-group, 'x')
          )
        run: |
          gh pr review --approve "$PR_URL"
          gh pr merge --auto --squash "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GH_TOKEN: ${{secrets.GITHUB_TOKEN}}
